### ISSUE TITLE
cannot find package in AUR. 

### ISSUE THREAD

**Issue by iravan** [Cangjians/cangjians.github.io#20]
`https://aur.archlinux.org/packages/?O=0&K=ibus-cangjie`
I cannot find the package in AUR so that the instruction of `http://cangjians.github.io/projects/ibus-cangjie/install.html` is incorrect.
Cannot install ibus-cangjie in Arch linux through pacman or yaourt yet.

**Comment by bochecha** [comment]
Weird, it used to be there.

@antonyho, what happened?

**Comment by antonyho** [comment]
> Between 2015-06-08 and 2015-08-08 the AUR transitioned from version 3.5.1 to 4.0.0, introducing the use of Git repositories for publishing the PKGBUILDs.

That's why the packages were not in new AUR repo. Packages are back again with the latest versions.

**Comment by bochecha** [comment]
Indeed, I see it there: https://aur.archlinux.org/packages/ibus-cangjie/

Thanks for the report @iravan, and thanks @antonyho for fixing the issue and maintaining IBus Cangjie in Arch!
